---
- hosts: aws
  gather_facts: False
  become: yes
  tasks:
    - name: install nginx
      yum:
        name: nginx
        state: installed
        update_cache: yes
        notify:
          - start nginx
        
  handlers:
    - name: start Nginx
      service: name=nginx state=started
